{ lib, ... }:

{
  imports = [
    ./files.nix
    ./hotkeys.nix
    ./shortcuts.nix
    ./GitKlientSettings
    ./akonadi
    ./akregator
    ./ark
    ./baloo
    ./breeze
    ./device_automounter_kcm
    ./discover
    ./dolphin
    ./elisa
    ./ffmpegthumbs
    ./fielding
    ./gravatar
    ./gwenview
    ./haruna
    ./kactivitymanagerd
    ./kactivitymanagerd-plugins
    ./kalarm
    ./kalendar
    ./kalendarcontact
    ./kalzium
    ./kblackbox
    ./kcalc
    ./kclock
    ./kcmcddb
    ./kcminput
    ./kde5
    ./kded_device_automounter
    ./kdeglobals
    ./kdenlive
    ./kdevelop
    ./kio_ftp
    ./kioslave
    ./kleopatra
    ./konsole
    ./kontact
    ./konversation
    ./korganizer
    ./kpat
    ./krunner
    ./kscreenlocker
    ./kshisen
    ./ksmserver
    ./kspaceduel
    ./ktouch2
    ./kwin
    ./kxkb
    ./marble
    ./neochat
    ./okular
    ./pimcommon
    ./plasma
    ./plasmadialer
    ./sieve
    ./skanpage
    ./spectacle
    ./templateparser
    ./touchpad
    ./umbrellorc
    ./undefined
    ./yakuake
  ];

  options.programs.plasma.enable = lib.mkEnableOption ''
    Enable configuration management for KDE Plasma.
  '';
}
