{ lib, ... }:

{
  imports = [
    ./files.nix
    ./hotkeys.nix
    ./shortcuts.nix
    ./GitKlientSettings.nix
    ./akonadi.nix
    ./akregator.nix
    ./ark.nix
    ./baloo.nix
    ./breeze.nix
    ./device_automounter_kcm.nix
    ./discover.nix
    ./dolphin.nix
    ./elisa.nix
    ./ffmpegthumbs.nix
    ./fielding.nix
    ./gravatar.nix
    ./gwenview.nix
    ./haruna.nix
    ./kactivitymanagerd.nix
    ./kactivitymanagerd-plugins.nix
    ./kalarm.nix
    ./kalendar.nix
    ./kalendarcontact.nix
    ./kalzium.nix
    ./kblackbox.nix
    ./kcalc.nix
    ./kclock.nix
    ./kcmcddb.nix
    ./kcminput.nix
    ./kde5.nix
    ./kded_device_automounter.nix
    ./kdeglobals.nix
    ./kdenlive.nix
    ./kdevelop.nix
    ./kio_ftp.nix
    ./kioslave.nix
    ./kleopatra.nix
    ./konsole.nix
    ./kontact.nix
    ./konversation.nix
    ./korganizer.nix
    ./kpat.nix
    ./krunner.nix
    ./kscreenlocker.nix
    ./kshisen.nix
    ./ksmserver.nix
    ./kspaceduel.nix
    ./ktouch2.nix
    ./kwin.nix
    ./kxkb.nix
    ./marble.nix
    ./neochat.nix
    ./okular.nix
    ./pimcommon.nix
    ./plasma.nix
    ./plasmadialer.nix
    ./sieve.nix
    ./skanpage.nix
    ./spectacle.nix
    ./templateparser.nix
    ./touchpad.nix
    ./umbrellorc.nix
    ./undefined.nix
    ./yakuake.nix
  ];

  options.programs.plasma.enable = lib.mkEnableOption ''
    Enable configuration management for KDE Plasma.
  '';
}
